#Test Jenkins Third Try
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
    restart: unless-stopped

  jenkins:
    build:
      context: ./jenkins
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"      # Jenkins UI
      - "50000:50000"    # Jenkins agent port
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./config:/wireguard-config:ro  # Mount wireguard config (read-only) supaya Jenkins bisa akses
      - /var/run/docker.sock:/var/run/docker.sock  # Supaya Jenkins bisa kontrol Docker
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    # Optional: kalau perlu akses sebagai root untuk deploy
    user: root

volumes:
  jenkins_home:
    driver: local
